"""rename address

Revision ID: 66018e959be9
Revises: f1a142bc2f75
Create Date: 2025-12-23 14:14:37.329335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66018e959be9'
down_revision = 'f1a142bc2f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###
