"""add department

Revision ID: f1a142bc2f75
Revises: 281e2ea5c385
Create Date: 2025-12-23 14:02:47.060588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a142bc2f75'
down_revision = '281e2ea5c385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('departments', 'address',
               new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments')
    op.alter_column('departments', 'location',
               new_column_name='address')
    # ### end Alembic commands ###
